// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCAH8sFQHT9W3ax4TdK6te7ja5heunbso',
    appId: '1:1034566902225:web:75d1bc244201aba81c40f0',
    messagingSenderId: '1034566902225',
    projectId: 'stockswim',
    authDomain: 'stockswim.firebaseapp.com',
    storageBucket: 'stockswim.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-nPB9hDjEEgoyReAvV02ryRY2dMe49ZA',
    appId: '1:1034566902225:android:bf0abc319603c58e1c40f0',
    messagingSenderId: '1034566902225',
    projectId: 'stockswim',
    storageBucket: 'stockswim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7I_0RC8SJYr0cNlUOx5XsvzN0vT01hj8',
    appId: '1:1034566902225:ios:85fca42063af2dac1c40f0',
    messagingSenderId: '1034566902225',
    projectId: 'stockswim',
    storageBucket: 'stockswim.firebasestorage.app',
    iosBundleId: 'com.example.stockapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7I_0RC8SJYr0cNlUOx5XsvzN0vT01hj8',
    appId: '1:1034566902225:ios:85fca42063af2dac1c40f0',
    messagingSenderId: '1034566902225',
    projectId: 'stockswim',
    storageBucket: 'stockswim.firebasestorage.app',
    iosBundleId: 'com.example.stockapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCAH8sFQHT9W3ax4TdK6te7ja5heunbso',
    appId: '1:1034566902225:web:4168fbba20190d871c40f0',
    messagingSenderId: '1034566902225',
    projectId: 'stockswim',
    authDomain: 'stockswim.firebaseapp.com',
    storageBucket: 'stockswim.firebasestorage.app',
  );
}
